### ISSUE TITLE
Event information needs category and name fields

### ISSUE THREAD

**Issue by Standard8** [mozilla/glean-dictionary#1433]
The Glean dictionary tells me the event name is e.g. [newtab.search.ad.click](https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/newtab_search_ad_click), but to access the event in via BigQuery, you need the event category and name.

Whilst you can go look at the code, maybe the Glean Dictionary should be pulling these out automatically?

**Comment by Iinh** [comment]
Glean Dictionary can only _guess_ the event name and category information from the metric name itself. For example, [this](https://github.com/mozilla/glean-dictionary/blob/main/etl/looker.py#L118) is how it extracts the event name and category for Looker, and although this works for most cases, it doesn't for metric with multiple `.` in its name such as [newtab.search.ad.click](https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/newtab_search_ad_click).

I thought of maybe fixing it by splitting by the last `.` instead of the first `.`, but I'm afraid this is still too hacky... Considering that we can more accurately get the name and category from `metrics.yaml`, I wonder if this problem might be better addressed upstream, maybe in [glean_parser](https://github.com/mozilla/glean_parser/blob/main/glean_parser/metrics.py#L305)? 

What do you think would be a good solution here @travis79 @badboy

**Comment by badboy** [comment]
`Metric` objects in `glean_parser` already expose `category` and `name`, so it's really a matter of exposing that in the probeinfo service.

**Comment by badboy** [comment]
I built this thing and I couldn't remember, but @chutten correctly reminded me: names cannot contain dots, only the category. So splitting at the right most `.` will give you the category and name.
