### ISSUE TITLE
Wrong email format in mozphab app 

### ISSUE THREAD

**Issue by Iinh** [mozilla/glean-dictionary#171]
Right now the notification email for mozphab is not in the right format: 

<img width="740" alt="wrongemail" src="https://user-images.githubusercontent.com/28797553/97454039-8dcbdf00-18f3-11eb-8e51-e98ae92f08c5.png">

This is due to an error in the source data https://probeinfo.telemetry.mozilla.org/glean/repositories. 

<img width="519" alt="source" src="https://user-images.githubusercontent.com/28797553/97454239-c4a1f500-18f3-11eb-8973-8d7ce55088ba.png">

We could update our email in the static data file to fix this, however I wonder if this could be better addressed by fixing it on a higher level.

**Comment by wlach** [comment]
@linh Yeah I'd say this is out of scope for the glean dictionary. The file causing problems here, would you care to submit a quick PR there? You can just use GitHub's "edit this file" since it's such a simple change.

https://github.com/mozilla/probe-scraper/blob/master/repositories.yaml

Aside: I'm a little surprised that `foo@bar.com@bar.com` is considered a valid email address, but apparently it is: 

* https://github.com/mozilla/probe-scraper/blob/78c73a02bc34de9c3d125bd8d5d3fea59ae8418a/schemas/repositories.json#L27
* https://json-schema.org/understanding-json-schema/reference/string.html#email-addresses

I'd say this problem is obscure/unlikely enough that it's not worth fixing at this point.
