### ISSUE TITLE
STMO query gen can point to tables not containing desired data

### ISSUE THREAD

**Issue by perrymcmanis144** [mozilla/glean-dictionary#1957]
When looking for some recently added events for iOS, a DS noticed that the tables appeared to not contain any. We were pretty certain that they should be there, and we had observed them for their desktop equivalent, QA had verified, etc. And, the desktop generation seemed to work as expected.

It turned out that the cause of this was that the query gen was pointed at `org_mozilla_ios_firefox.events`. (Android, similarly, points to an org_mozilla table)

<img width="827" alt="image" src="https://github.com/mozilla/glean-dictionary/assets/95651456/7e9d161a-62ba-4b95-b0b4-4a08f7954401">

It turns out that this table doesn't actually have any of these events populated, switching over to `firefox_ios.events` and they show up. Desktop, comparatively uses `firefox_desktop.events`, and I wonder if we should switch the query gen for ios/android to point at firefox_ios, OR if it's actually desktop that is incorrect, and it should be an org_mozilla table too and I need to ping a DE about why those events don't seem to show up there.

FWIW the `channel` filter appears not to work at all in the org_moz tables even looking at all events.

**Comment by fbertsch** [comment]
The `firefox_ios.events` table is a unioned view of the three release app-ids ([see the definition here](https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/firefox_ios/events/view.sql)).

My guess is that the events hadn't hit release yet, which is why they were showing in the unioned view but not the release table.

Desktop has just a single channel, [see the repositories.yaml definition here](https://github.com/mozilla/probe-scraper/blob/main/repositories.yaml#L257-L259) (and it points to the `firefox_desktop` dataset).

**What to do, what to do**
One option is we drop the application variant filter entirely from the Glean Dictionary. This would simplify the experience, and I don't know how often people actually want see the data from e.g. just nightly or beta.

Another is to keep the variant filter, point to the app-name datasets (e.g. `firefox_ios` and `fenix`), and add that filter in the queries/explores.

There is an issue for the broken channel filters: https://github.com/mozilla/glean-dictionary/issues/1802

**Comment by perrymcmanis144** [comment]
My instinct is that channel is quite useful, not only as a filter but for analysis of newly implemented telemetry. 

I can't speak for everyone else. Perhaps selfishly, I like that it's there even if all it does is remind folks to be mindful that channels are an important consideration in looking at newly added data.

**Comment by fbertsch** [comment]
> My instinct is that channel is quite useful, not only as a filter but for analysis of newly implemented telemetry.

I don't disagree. In that case maybe the Glean Dictionary should:
1. Know how to handle both Desktop's channels (all go to the same app-id), and how to handle the variant channels (how ios & fenix do it). All of these should be exposed explicitly as "Channels", not "Variants".
2. Point Looker & SQL queries to the app-name datasets (`firefox_desktop`, `fenix`, `firefox_ios`) and filter on the channel in those queries

**Comment by Dexterp37** [comment]
Note that this is likely fixed by #1960

**Comment by Dexterp37** [comment]
This was fixed by #1960
