### ISSUE TITLE
Glean client info metrics (e.g. device_model) are handled incorrectly

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#248]
Currently the Glean dictionary is surfacing metrics like `device_model` which are instead supposed to appear in every ping as being in a non-existent ping called `glean_client_info`:

![image](https://user-images.githubusercontent.com/20569/101219535-2c193600-3652-11eb-8b2a-a9628da3a914.png)
https://glean-dictionary-dev.netlify.app/#!/apps/fenix/metrics/device_model

I'm guessing we should be smart enough to recategorize anything marked as `glean_client_info` as being present in every ping? I assume that our existing data pipeline deals with this... somewhere? @mdboom @badboy do you have thoughts here?

P.S. I notice these "metrics" are also in GLAM, but trigger a 404: https://glam-stage.bespoke.nonprod.dataops.mozgcp.net/fenix/probe/device_model/explore?ping_type=*&ref= /cc @robhudson

**Comment by badboy** [comment]
For general context: all "pings" that start with `glean_` are reserved.
For more detail (documented here): https://mozilla.github.io/glean/book/dev/core/internal/reserved-ping-names.html:
We have 2 "special" pings:

1. `glean_client_info` maps to the `client_info` section
2. `glean_internal_info` maps to the `ping_info`

Both sections are in every ping, however some fields in `client_info` might not be (such as client_id, see [pings](https://mozilla.github.io/glean/book/user/pings/index.html#the-client_info-section)).
Additionally the `experiments` field is currently documented as a `string` due to the lack of a better metric type (but the idea is that the schema generator can use these definitions to generate the schema).

So in total:
Yes, the `client_info` fields should be documented to be in every ping.
pings have a field `include_client_id` which determines whether `client_id` is actually included. If that's not surfaced on the indiviual client_info entry for now it should be fine.
Other optional fields are harder (e.g. `android_sdk_version` only exists on Glean Kotlin for obvious reasons, whereas `app_channel` depends on whether the app sets it.

**Comment by wlach** [comment]
Thanks @badboy -- looks like this is just a bug which we should fix.

**Comment by wlach** [comment]
I am wondering if this type of correction/transformation might be better done in probe-scraper, in line with the philosophy behind @jklukas's proposal here: https://docs.google.com/document/d/1_zx0cxBnnFOhct1cCb_QnXntV-HN9sjqfGfiBwEBL-8/edit?disco=AAAAK-qYzzw

I believe this would require translating these "metrics" out of these glean-specific files, and re-specifying them in the context of the application -- in my mind, this would be part of the `/v2/` API hinted at in the proposal.

**Comment by jklukas** [comment]
It looks like the [schema pipeline handles this within m-s-g](https://github.com/mozilla/mozilla-schema-generator/blob/9df85aed48c1cf6012a744673ca0ec3050471c27/mozilla_schema_generator/glean_ping.py#L34-L40), listing a specific set of pings to ignore, and then also handles the logic of resolving dependencies.

I do think it makes sense long-term to prepare a "fully-baked" per-app probeinfo endpoint for metrics, that would include the metrics that come from dependencies. Currently, it would be necessary for the glean dictionary to duplicate this resolution logic. If that's the view that we would normally want to see, then I think it makes sense to have the `/v2/glean/application/{document_namespace}/metrics` endpoint be in that format.

**Comment by wlach** [comment]
This just confused someone on #data-help in slack, we should probably fix this before we announce. Doing up a hacky fix inside glean-dictionary's etl-- the right solution is to do this type of correction inside probe-scraper.
