### ISSUE TITLE
Backlinks from BigQuery view -> Metric don't work

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#313]
In the BigQuery view, we currently have a backlink to the metric that generated it.

![image](https://user-images.githubusercontent.com/20569/104342050-6df69100-54c8-11eb-8385-f1c679cc967d.png)

But the link is often wrong. For example for:

https://glean-dictionary-dev.netlify.app/apps/firefox-android-release/tables/metrics?search=metrics.string_list.addons_enabled_addons

The link should be:

https://glean-dictionary-dev.netlify.app/apps/firefox-android-release/metrics/addons-enabled_addons

But actually is:

https://glean-dictionary-dev.netlify.app/apps/firefox-android-release/metrics/addons_enabled_addons

**Comment by Fenn-CS** [comment]
Picking this up.

**Comment by wlach** [comment]
> Picking this up.

@Fenn-CS do you think you'll have time to work on this in the next day or so? We were hoping to do a release soon, if not that's cool but we might assign this to someone else.

**Comment by Fenn-CS** [comment]
@wlach should look at this tomorrow!

**Comment by Fenn-CS** [comment]
@wlach What are the rules around constructing these url's?  I can see that in :
https://github.com/mozilla/glean-dictionary/blob/8d16f8eb1a71a5efbda790598215980b700bb5cf/src/components/SchemaNode.svelte#L34

The problemactic part `addons_enabled_addons` instead of  `addons-enabled_addons` (first hyphen underscore should be hyphen), is gotten from : 

https://github.com/mozilla/glean-dictionary/blob/8d16f8eb1a71a5efbda790598215980b700bb5cf/src/pages/TableDetail.svelte#L15-L22


Which effectively translates to fetching : https://raw.githubusercontent.com/mozilla-services/mozilla-pipeline-schemas/generated-schemas/schemas/org-mozilla-firefox/metrics/metrics.1.bq

Looking at the file, the guiding rule or rule for generation is not clear to me. I have thought about a way to fix this by breaking the `node.name` and extracting attaching `addions-` before appending the rest. However that's not a rule and it might break in another scenario.

**Comment by wlach** [comment]
@Fenn-CS Great detective work. What an interesting issue! Basically we're dealing with the fact that we're not using `.` in BigQuery table columns, because that would be confusing and/or invalid, so we translate those into underscores instead. Haven't checked, but I suspect the code that does this in  [mozilla-schema-generator](https://github.com/mozilla/mozilla-schema-generator).

Inside glean-dictionary, we actually translate `.` to `-` for a slightly different reason (so as not to make the software we're using to serve think that a metric is a real file): https://github.com/mozilla/glean-dictionary/blob/main/src/state/urls.js#L5

I think the solution is to just translate `.`s to `_` everywhere instead -- in theory this *could* break in some cases (since I don't think anything in Glean would disallow two metric names, one like `foo_bar.baz_bar` and another like `foo_bar_baz.bar`), but in practice it's extremely unlikely (~impossible). 

To do this you'll need to modify:

* `urls.js` above
* `ItemList.svelte` in `src/components`
* maybe one or two other things (test around a bit after making the change)

**Comment by Fenn-CS** [comment]
@wlach Sorry if I am missing something, but changing all `.`s to `_` would create issues finding the file on the file system would it not?

Look at the actual files being fetch 
```
├── about_page.libraries_tapped.json
├── about_page.licensing_tapped.json
├── about_page.privacy_notice_tapped.json
├── about_page.rights_tapped.json
├── about_page.support_tapped.json
├── activation.activation_id.json
├── activation.identifier.json
├── addons.enabled_addons.json
├── addons.has_enabled_addons.json
├── addons.has_installed_addons.json
├── addons.installed_addons.json
├── addons.open_addon_in_toolbar_menu.json
├── addons.open_addons_in_settings.json
├── android_sdk_version.json
├── app_build.json
├── app_channel.json
├── app_display_version.json
├── app_theme.dark_theme_selected.json
├── architecture.json
```

Since underscores already exists in the metrics names, replacing everything with underscore means we would need a trial and error algorithm that tests for the position where the `.` is found to actual fetch metrics. Something like the one below

```js
export async function getMetricData(appName, metricName) {
    let metricData;
    let underScoreReplace = 1;
    let parts = metricName.split('_');
    while (!metricData) {
        console.log(underScoreReplace)
        let tempParts = parts;
        let end = tempParts.splice(underScoreReplace).join('_');
        tempParts = parts;
        let start = tempParts.splice(0, underScoreReplace).join('_');
        let tempName = `${start}.${end}`;
        metricData = await fetchJSON(`/data/${appName}/metrics/${tempName}.json`);
        underScoreReplace++;
    }
    return metricData;
}
```

From 

https://github.com/mozilla/glean-dictionary/blob/8d16f8eb1a71a5efbda790598215980b700bb5cf/src/state/api.js#L16-L18

**Comment by wlach** [comment]
> @wlach Sorry if I am missing something, but changing all `.`s to `_` would create issues finding the file on the file system would it not?

Hey, that's correct. 😄 However we should be able to change the names of the files we write by modifying this:

https://github.com/mozilla/glean-dictionary/blob/6577fd2fd2a4bc04e871d6605dee76aee7ef166e/scripts/build-glean-metadata.py#L117

Sorry for not mentioning this before.
