### ISSUE TITLE
Probe description does not support <br> HTML or list item markdown

### ISSUE THREAD

**Issue by mcomella** [mozilla/glean-dictionary#642]
The old metrics.md supported html tags like `<br>` and list items (lines starting with `-`) ([example](https://github.com/mozilla-mobile/fenix/blob/releases_v89.0.0/docs/metrics.md):
![image](https://user-images.githubusercontent.com/759372/120526524-221c8980-c38e-11eb-8a0c-9252def0481e.png)

However, the probe dictionary doesn't support it ([example](https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/events_app_opened_all_startup)):
![image](https://user-images.githubusercontent.com/759372/120526595-38c2e080-c38e-11eb-84e8-29b0361cc312.png)

Without lists or the ability to add paragraphs, it makes it difficult (for me) to write information about complex probes clearly.

**Comment by wlach** [comment]
Yeah, we intentionally escape some of the markdown in the description. The problem was that people were unintentionally adding HTML tags (without quoting) in the metrics files, which caused weird issues on occasion (see e.g. mozilla-mobile/fenix#19243). On reflection, the right answer is probably just to fix these issues in the source, rather than remove flexibility on what people can do to avoid footguns. I'll try to address this.

That said, lists and paragraphs are supported in markdown without having to write HTML, using [plain old markdown syntax](https://daringfireball.net/projects/markdown/syntax). You should be able to express what you need to for your metric above in a more legible way by doing that.

**Comment by mcomella** [comment]
> That said, lists and paragraphs are supported in markdown without having to write HTML, using [plain old markdown syntax](https://daringfireball.net/projects/markdown/syntax). You should be able to express what you need to for your metric above in a more legible way by doing that.

Ah, this wasn't the case in the metrics.md file so I used HTML tags to work around it. 😆  It sounds better to just use markdown though – I'll do this going forward.

**Comment by wlach** [comment]
I filed a bug in glean parser to handle invalid HTML in the future: https://bugzilla.mozilla.org/show_bug.cgi?id=1733256

I'm going to just literally render anything passed in for the Glean Dictionary from now on, PR incoming...
