### ISSUE TITLE
Add searchfox links for metrics

### ISSUE THREAD

**Issue by mdboom** [mozilla/glean-dictionary#65]
It would be super handy to provide searchfox search URLs that search the code base for uses of a given metric.  It should be enough to search for `category_name.metric_name` as a string.

Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1668547

**Comment by wlach** [comment]
Let's try to implement this for the MVP, need to spec out a few things before it's ready for a contributor to tackle though.

**Comment by wlach** [comment]
I think this is ready to look at. We can start just by searching searchfox (which has most of the products we care about, see "repositories" at https://searchfox.org/) for metric names.

I think mostly this is about creating a searchfox link in the metrics page. This is analagous to the view that the probe dictionary has:

![image](https://user-images.githubusercontent.com/20569/102907372-f347d200-4443-11eb-98e3-93dd95727e80.png)
https://probes.telemetry.mozilla.org/?view=detail&probeId=histogram%2FA11Y_CONSUMERS

We could probably use a more descriptive title than "Find in", but that can happen in a followup.

Notes:

* I think for an MVP of this we can create a manual mapping of products to searchfox URLs in this repository. Later we could investigate moving that metadata into probe-scraper
* For Firefox desktop, search indexing can work with this type of query: https://searchfox.org/mozilla-central/search?q=fog.ipc.replay_failures
* Many other products are indexed under https://searchfox.org/mozilla-mobile/source/ -- you'll want to restrict to the path when searching e.g. for Firefox Reality's `distribution.channel_name` metric you would want this: https://searchfox.org/mozilla-mobile/search?q=distribution.channel_name&path=FirefoxReality
* If a metric is expired and no longer in the source repository, the search will fail. #23 will make this a less obvious footgun (since it will be harder to discover obsolete metrics)
