### ISSUE TITLE
Provide sample queries on table page

### ISSUE THREAD

**Issue by jklukas** [mozilla/glean-dictionary#787]
On a BQ table page, we list "live data" and "stable view", each with a table/view qualified at the namespace level. Users may be lacking context for what these terms mean, so we should provide an info field that links to the "table layout and naming" section of DTMO (https://docs.telemetry.mozilla.org/cookbooks/bigquery/querying.html#table-layout-and-naming) and provide some immediate message about how the live tables are generally not considered user-facing and should usually only be used for debugging purposes tracking new telemetry.

Additionally, we could provide sample queries to provide more complete guidance about how to start investing these views and encouraging efficient use of partitioning, clustering, and limiting. For stable views, the example could be:

```
SELECT
  *
FROM
  mozdata.org_mozilla_firefox.events  # We'd inject the view name here
WHERE
  DATE(submission_timestamp) = (CURRENT_DATE() - 1)
LIMIT
  10
```

That codifies the pattern of looking at just the most recent day, limiting to just a few records, and fully qualifying the name with the `mozdata` project (so that this example should work regardless of which project it's launched from).

A live example could be:

```
SELECT
  *
FROM
  `moz-fx-data-shared-prod.org_mozilla_firefox_live.events_v1`
WHERE
  submission_timestamp > (CURRENT_TIMESTAMP() - INTERVAL 1 HOUR)
LIMIT
  10
```

Here, we pick just the most recent hour of data (since live tables are clustered on submission_timestamp) and again have a limit. Also note that we fully qualify with `moz-fx-data-shared-prod` which is necessary since we do not automatically publish views for live data in the `mozdata` project.

It's not entirely clear to me how it would be best to present example queries. It may be ideal to have these as some sort of expandable item alongside the "live data" and "stable view" listings.

**Comment by wlach** [comment]
Thanks for filing this Jeff. Adding some info items and docs links should be easy, I'll get started on that right away.

Wrt examples, I'd be inclined to just refer to docs.telemetry.mozilla.org for details on how to make the queries, at least for now. In general I expect we'll be increasingly be encouraging people to use Looker to access Glean data, and streamlining the workflow of making manual SQL queries doesn't seem like right place to put our efforts (please let me know if you disagree!).

For stable queries, we already have https://docs.telemetry.mozilla.org/cookbooks/accessing_glean_data.html (feel free to suggest additions or improvements to that, as we're linking to it from an increasing number of places).

For live data, we have https://docs.telemetry.mozilla.org/cookbooks/view_pings_cep.html which could be adapted to incorporate the glean-based example you mentioned without much effort (while we're at it, I'd dump that tutorial in the "BigQuery" cookbook subheading, rather than putting it in its own "Realtime" category).

**Comment by jklukas** [comment]
> streamlining the workflow of making manual SQL queries doesn't seem like right place to put our efforts

That's an entirely reasonable assessment :)



> For stable queries, we already have https://docs.telemetry.mozilla.org/cookbooks/accessing_glean_data.html (feel free to suggest additions or improvements to that, as we're linking to it from an increasing number of places).


That link looks like it's probably the right thing to be the primary link in the info box for "stable view".



> For live data, we have https://docs.telemetry.mozilla.org/cookbooks/view_pings_cep.html which could be adapted to incorporate the glean-based example you mentioned without much effort (while we're at it, I'd dump that tutorial in the "BigQuery" cookbook subheading, rather than putting it in its own "Realtime" category).

AFAIK, there's generally no easy way to determine your own client_id in Glean apps, including Fenix. So I don't think there's any way to adapt the "view your own pings" idea to a Glean-based one.

**Comment by wlach** [comment]
> AFAIK, there's generally no easy way to determine your own client_id in Glean apps, including Fenix. So I don't think there's any way to adapt the "view your own pings" idea to a Glean-based one.

Right, and we have the glean ping viewer for that sort of thing. However, I think being able to monitor the stream of incoming live pings is something that deserves a short tutorial and this seems like a good place to do it. I don't think we need to restrict ourselves to the original concept of "viewing your own pings".
