### ISSUE TITLE
Table search only searches in last part of the component

### ISSUE THREAD

**Issue by wlach** [mozilla/glean-dictionary#80]
*This issue is intended as an onboarding task for potential outreachy applicants. Please do not work on it unless you have completed the initial qualification task and it has been assigned to you.*

Currently the filter search in the table view (e.g. http://localhost:5000/#!/apps/mach/tables/usage) only filters for content in the last "node" in the structure. e.g. if you have

```
client_info.app_version
client.info.app_display_version
client_info.client_id
...
```

and you search for "client", it will filter out all of the above except for `client_info.client_id`. Ideally the search would include all entries whose parent elements have the term in them (in the example above, this would be everything that includes `client`).

To fix this, you'll need to edit the schemaviewer component: https://github.com/mozilla/glean-dictionary/blob/0a54d6fee06c9031852fb96b19657c598ddbd1e9/src/components/SchemaViewer.svelte#L8

**Comment by wlach** [comment]
Going to assign this to @hngerebara

**Comment by UdokaVrede** [comment]
Hi wlach how can I locate the initial qualification task

**Comment by mhmohona** [comment]
Hello @UdokaVrede! I am another outreachy applicant like you but as @wlach is currently on vacation and will be available from Monday, I am replying you.
 
In project Outreachy [website](https://www.outreachy.org/outreachy-december-2020-internship-round/communities/mozilla/#extend-glean-dictionary) you will find details about initial qualification task. 


These are steps mentioned there in website - 

The first step of the application process is to:    
 
* If you haven't used Svelte before (which is ok!), run through at least some of their interactive tutorial: https://svelte.dev/tutorial/basics
* Checkout the glean dictionary project (https://github.com/mozilla/glean-dictionary)
* Following the instructions in the README, extract and process the dataset information and get a local copy of the site running
* Find the "usage ping" BigQuery table for the "mach" application and find the client_info.app_channel column. Using your text editor and the locally checked out source, make it so that the description of the column is shown in RED rather than the current colour of GREY
* Take a screenshot and create a diff of the changes you made to make this change, and DM these to `wlach` on chat.mozilla.org (see the project communications channels) along with your GitHub user id

**Comment by UdokaVrede** [comment]
Thanks
